# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       libcontentaction

# >> macros
# << macros

Summary:    Library for associating content with actions
Version:    0.1.92
Release:    1
Group:      System/Desktop
License:    LGPLv2.1
URL:        https://github.com/nemomobile/libcontentaction
Source0:    %{name}-%{version}.tar.bz2
Source100:  libcontentaction.yaml
Requires:   libcontentaction-qt5
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(mlite)
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  pkgconfig(QtDBus)
BuildRequires:  pkgconfig(QtTest)
BuildRequires:  pkgconfig(QtXml)
BuildRequires:  pkgconfig(QtSystemInfo)
BuildRequires:  python

%description
libcontentaction is a library for associating content with actions.


%package devel
Summary:    Development files for libcontentaction
Group:      Development/System
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains development files for building applications using
libcontentaction library.


%package tests
Summary:    Tests for libcontentaction
Group:      System/X11
Requires:   %{name} = %{version}-%{release}
Requires:   dbus-python
Requires:   pygobject2
Requires:   python
Requires:   tracker-utils
Requires:   qt4-default
Requires:   libqtdbus4

%description tests
This package contains the tests for libcontentaction library.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libdir}/libcontentaction.so.*
%exclude %{_datadir}/applications/defaults.list
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/contentaction/contentaction.h
%{_includedir}/contentaction/contentinfo.h
%{_libdir}/libcontentaction.so
%{_libdir}/pkgconfig/contentaction-0.1.pc
# >> files devel
# << files devel

%files tests
%defattr(-,root,root,-)
%attr(0755, root, root) /opt/tests/libcontentaction/bin/lca-cita-test
/opt/tests/libcontentaction/*
# >> files tests
# << files tests
