#!/bin/sh

TEST_DIR="/opt/tests/libcontentaction/"

set -e
. ${HOME}/.eat-stored-env
mkdir -p ${HOME}/tests-home
cd ${TEST_DIR}
PATH=${TEST_DIR}/bin/:${TEST_DIR}:$PATH XDG_DATA_HOME=${HOME}/tests-home/ CONTENTACTION_ACTIONS=${TEST_DIR}/data $@

